name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - name: Install Node.js v19
        uses: actions/setup-node@v1
        with:
          node-version: 19.9.0
          corepack-enable: true
      - name: Install packages
        run: yarn install
      - name: Build project
        run: yarn run build
      - name: Lint
        run: yarn run lint
